"""Web panel — REST API + static single-page UI.

The visual layer of "organization as code": creating an amele from the
panel writes ameles/<slug>.yaml (an amele amele) and a database row.
Deleting an amele is deleting a file + row. Everything else the panel
does (items, settings, history) is plain CRUD on the same SQLite file
the scheduler and bot use.

Auth: PBKDF2-hashed panel password, session cookie, brute-force lockout
(5 failed attempts → 5 min), env fallback (KAHYA_ADMIN_PASSWORD).
"""
from __future__ import annotations

import json
import os
import re
import secrets
import subprocess
import time
from http.cookies import SimpleCookie
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import parse_qs, urlparse
import urllib.parse
import urllib.request

from .amele_runner import AmeleError, run_amele
from .config import Config, DEFAULT_ADMIN_PASSWORD, hash_password, verify_password
from .db import KahyaDB
from .i18n import I18n

AMELE_TEMPLATE = """# {slug} — {name}
# Generated by the Kahya web panel. This file IS the amele — version it,
# diff it, share it ("organization as code").
#
# The scheduler hands it timed tasks:
#   TASK event=time record_id=<id> now=<YYYY-MM-DD HH:MM>

model: ${{AMELE_MODEL}}

provider:
  type: ${{PROVIDER_TYPE}}
  base_url: ${{BASE_URL}}
  api_key: ${{API_KEY}}

system_prompt: |
{role_prompt}
  Standard rules for every Kahya amele:
  - You receive TASK messages from the scheduler or from Kâhya (the
    orchestrator). For a timed task: fetch your record with db_get
    (op=get, id=<id>), then send ONE short message with telegram_send —
    what it is, when it is due, and a clear note if due is now or overdue.
  - Write records only through db_put; your records live in your own
    database namespace (KAHYA_AMELE_ID). Never invent records, dates or
    amounts. Output must always be valid JSON.

workspace: .

tools:
  fs: false
  subprocess:
    - name: db_get
      description: >
        Read records from the Kahya database. stdin: JSON — either
        {{"op": "get", "id": <int>}} for one record, {{"op": "list"}} for
        your records, or {{"op": "search", "q": "<text>"}}. stdout: the
        record(s) as JSON (field "data" holds the record body).
      command: ["../tools/db_get.py"]
      timeout: 30s
    - name: db_put
      description: >
        Write a record to the Kahya database (your own namespace). stdin:
        JSON — {{"op": "put", "data": {{...}}}} creates a record,
        {{"op": "put", "id": <int>, "data": {{...}}}} updates one,
        {{"op": "delete", "id": <int>}} removes one. stdout: {{"id": N}}
        or an error. Invalid JSON or schema violations are rejected.
      command: ["../tools/db_put.py"]
      timeout: 30s
    - name: telegram_send
      description: >
        Send a text message to the owner on Telegram. stdin: the message
        text. stdout: "ok" or an error message.
      command: ["../tools/telegram_send.py"]
      timeout: 60s
    - name: ask_confirm
      description: >
        Ask the owner to approve a risky/destructive action (sending
        money, deleting, publishing, paying...). stdin: {{"soru": "what
        you want to do", "aksiyon": {{...details...}}}}. stdout:
        {{"onay_id": N}}. The owner replies with plain text
        (evet/hayır/iptal); the bot routes it back to you. NEVER perform
        the action without approval.
      command: ["../tools/ask_confirm.py"]
      timeout: 60s

limits:
  max_turns: 10
  max_tokens: 20000
  timeout: 3m
"""

SLUG_RE = re.compile(r"^[a-z0-9][a-z0-9-]{1,30}$")
MAX_FAILED = 5
LOCK_MINUTES = 5
COOKIE = "kahya_session"


class Handler(BaseHTTPRequestHandler):
    server_version = "Kahya/0.2"

    # ---------------------------------------------------------- helpers

    def _json(self, obj, code=200):
        body = json.dumps(obj, ensure_ascii=False).encode()
        self.send_response(code)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def _read_body(self) -> dict:
        length = int(self.headers.get("Content-Length") or 0)
        if not length:
            return {}
        try:
            return json.loads(self.rfile.read(length).decode() or "{}")
        except json.JSONDecodeError:
            return {}

    def _query(self, key: str):
        vals = parse_qs(urlparse(self.path).query).get(key)
        return vals[0] if vals else None

    def _session_token(self) -> str | None:
        raw = self.headers.get("Cookie") or ""
        c = SimpleCookie()
        c.load(raw)
        m = c.get(COOKIE)
        return m.value if m else None

    def _authed(self) -> bool:
        token = self._session_token()
        return bool(token) and self.server.db.session_valid(token)

    def _require_auth(self) -> bool:
        if self._authed():
            return True
        if self.path == "/login" or self.path == "/api/login":
            return True
        self._json({"error": "unauthorized"}, 401)
        return False

    # ------------------------------------------------------------ routes

    def do_GET(self):
        path = urlparse(self.path).path
        if path == "/login":
            self._serve_web()
            return
        if path == "/" or path == "/index.html":
            self._serve_web()
            return
        if path == "/api/lang":
            lang = self._query("lang") or self.server.cfg.language
            self._json(I18n(self.server.cfg.dir / "lang", lang).data())
            return
        if not self._require_auth():
            return
        if path == "/api/me":
            self._json({"ok": True,
                        "using_default_password": self.server.cfg.admin_password_hash == ""
                                                   and self.server.cfg.env_admin_password() is None})
            return
        if path == "/api/v2/overview":
            self._v2_overview()
            return
        if path == "/api/v2/ameles":
            self._v2_ameles_get()
            return
        if path == "/api/v2/records":
            self._v2_records_get()
            return
        if path == "/api/v2/approvals":
            self._v2_approvals_get()
            return
        if path == "/api/v2/tasks":
            self._v2_tasks_get()
            return
        if path == "/api/v2/mcp":
            self._v2_mcp_get()
            return
        if path == "/api/v2/mcp/search":
            self._v2_mcp_search()
            return
        if path == "/api/v2/mcp/status":
            self._v2_mcp_status()
            return
        if path == "/api/settings":
            self._json({"settings": self.server.cfg.all_editable()})
            return
        if path == "/api/backup":
            self._send_backup()
            return
        if path == "/api/backup/history":
            self._send_history_backup()
            return
        self._json({"error": "not found"}, 404)

    def do_POST(self):
        path = urlparse(self.path).path
        if path == "/api/login":
            self._login()
            return
        if path == "/api/logout":
            self._logout()
            return
        if not self._require_auth():
            return
        if path == "/api/v2/ameles":
            self._v2_ameles_create()
            return
        if path == "/api/v2/ameles/edit":
            self._v2_ameles_edit()
            return
        if path == "/api/v2/ameles/delete":
            self._v2_ameles_delete()
            return
        if path == "/api/v2/records":
            self._v2_records_create()
            return
        if path == "/api/v2/records/edit":
            self._v2_records_edit()
            return
        if path == "/api/v2/records/delete":
            self._v2_records_delete()
            return
        if path == "/api/v2/approvals/resolve":
            self._v2_approvals_resolve()
            return
        if path == "/api/v2/mcp/servers":
            self._v2_mcp_servers_create()
            return
        if path == "/api/v2/mcp/servers/delete":
            self._v2_mcp_servers_delete()
            return
        if path == "/api/v2/mcp/bind":
            self._v2_mcp_bind()
            return
        if path == "/api/v2/mcp/unbind":
            self._v2_mcp_unbind()
            return
        if path == "/api/v2/mcp/explain":
            self._v2_mcp_explain()
            return
        if path == "/api/v2/mcp/login":
            self._v2_mcp_login()
            return
        if path == "/api/settings":
            self._save_settings()
            return
        if path == "/api/test/telegram":
            self._test_telegram()
            return
        if path == "/api/test/llm":
            self._test_llm()
            return
        self._json({"error": "not found"}, 404)

    # -------------------------------------------------------------- auth

    def _login(self):
        db = self.server.db
        if db.failed_logins(LOCK_MINUTES) >= MAX_FAILED:
            self._json({"error": "locked"}, 429)
            return
        data = self._read_body()
        user = str(data.get("user") or "")
        password = str(data.get("password") or "")
        cfg = self.server.cfg

        env_pass = cfg.env_admin_password()
        ok = False
        if env_pass is not None:
            ok = (user == cfg.admin_user and secrets.compare_digest(password, env_pass))
        else:
            stored = cfg.admin_password_hash
            if stored != "":
                ok = (user == cfg.admin_user and verify_password(password, stored))
            else:
                # first run: default credentials, warned in the panel
                ok = (user == cfg.admin_user
                      and secrets.compare_digest(password, DEFAULT_ADMIN_PASSWORD))

        db.record_login(ok)
        if not ok:
            self._json({"error": "bad_credentials"}, 401)
            return
        token = secrets.token_hex(24)
        db.create_session(token)
        self.send_response(200)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Set-Cookie",
                         f"{COOKIE}={token}; HttpOnly; Path=/; Max-Age=86400; SameSite=Lax")
        body = json.dumps({"ok": True}).encode()
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def _logout(self):
        token = self._session_token()
        if token:
            self.server.db.delete_session(token)
        self._json({"ok": True})

    # ------------------------------------------------------------- files

    def _serve_web(self):
        p = self.server.web_dir / "index.html"
        if not p.exists():
            self._json({"error": "web/index.html missing"}, 500)
            return
        body = p.read_bytes()
        self.send_response(200)
        self.send_header("Content-Type", "text/html; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def _send_backup(self):
        db_path = self.server.cfg.db_path
        if not db_path.exists():
            self._json({"error": "db missing"}, 500)
            return
        body = db_path.read_bytes()
        self.send_response(200)
        self.send_header("Content-Type", "application/octet-stream")
        self.send_header("Content-Disposition",
                         f'attachment; filename="kahya-backup-{db_path.stat().st_mtime:.0f}.db"')
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def _send_history_backup(self):
        db = self.server.db
        rows = db.con.execute(
            "SELECT thread_id, role, content, ts, archived "
            "FROM conversation_messages ORDER BY id").fetchall()
        from datetime import datetime
        payload = {
            "exported_at": datetime.now().isoformat(timespec="seconds"),
            "kayit_sayisi": len(rows),
            "mesajlar": [dict(r) for r in rows],
        }
        body = json.dumps(payload, ensure_ascii=False, indent=1).encode()
        self.send_response(200)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Disposition",
                         f'attachment; filename="kahya-gecmis-{int(time.time())}.json"')
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    # ------------------------------------------------------------- v2: overview

    def _amele_yaml_text(self, slug: str, name: str, role_prompt: str) -> str:
        role_indented = "\n".join("  " + ln for ln in role_prompt.splitlines())
        return AMELE_TEMPLATE.format(slug=slug, name=name, role_prompt=role_indented)

    def _v2_overview(self):
        db = self.server.db
        from datetime import datetime, timedelta
        now = datetime.now()
        soon = (now + timedelta(days=7)).strftime("%Y-%m-%d %H:%M:%S")
        tasks = []
        for t in db.list_scheduled_tasks("pending"):
            amele = db.get_amele(t["amele_id"])
            row = dict(t)
            row["amele_slug"] = amele["slug"] if amele else "?"
            row["gecikti"] = t["run_at"] < now.strftime("%Y-%m-%d %H:%M:%S")
            if t["run_at"] <= soon:
                tasks.append(row)
        self._json({
            "ameles": len(db.list_ameles()),
            "kayitlar": db.count_records(),
            "bekleyen_onaylar": len(db.list_pending_actions("waiting")),
            "bekleyen_gorevler": len(db.list_scheduled_tasks("pending")),
            "yaklasan_gorevler": tasks,
        })

    # ------------------------------------------------------------- v2: ameles

    def _v2_ameles_get(self):
        out = []
        for a in self.server.db.list_ameles():
            d = dict(a)
            for k in ("schema_json", "model_cfg"):
                try:
                    d[k] = json.loads(d[k]) if d.get(k) else None
                except (TypeError, json.JSONDecodeError):
                    d[k] = None
            out.append(d)
        self._json({"ameles": out})

    def _v2_ameles_create(self):
        data = self._read_body()
        db = self.server.db
        slug = (data.get("slug") or "").strip().lower()
        name = (data.get("name") or "").strip()
        role = (data.get("description") or "").strip()
        if not SLUG_RE.match(slug):
            self._json({"error": "slug: 2-32 chars, a-z0-9 and dashes only"}, 400)
            return
        if not name or not role:
            self._json({"error": "name and description are required"}, 400)
            return
        if db.get_amele_by_slug(slug):
            self._json({"error": f"amele '{slug}' already exists"}, 409)
            return
        model_kind = data.get("model_kind") or "local"
        if model_kind not in ("local", "api"):
            self._json({"error": "model_kind: local|api"}, 400)
            return
        model_name = (data.get("model_name") or "").strip()
        model_cfg = data.get("model_cfg") if isinstance(data.get("model_cfg"), dict) else None
        if model_kind == "api":
            if not model_name:
                self._json({"error": "model_name gerekli (api modeli)"}, 400)
                return
            if not (model_cfg and model_cfg.get("base_url")):
                self._json({"error": "model_cfg.base_url gerekli (api modeli)"}, 400)
                return
        elif not model_name:
            model_name = "qwen3:27b"
        schema = data.get("schema_json") if isinstance(data.get("schema_json"), dict) else None
        yaml_path = self.server.ameles_dir / f"{slug}.yaml"
        yaml_path.write_text(self._amele_yaml_text(slug, name, role), encoding="utf-8")
        amele_id = db.create_amele(slug, name, role, str(yaml_path),
                                   model_kind=model_kind, model_name=model_name,
                                   model_cfg=model_cfg, schema_json=schema)
        db.log("web", {"event": "amele_created", "amele": slug})
        self._json({"ok": True, "id": amele_id, "slug": slug}, 201)

    def _v2_ameles_edit(self):
        data = self._read_body()
        db = self.server.db
        amele = db.get_amele(int(data.get("id") or 0))
        if not amele:
            self._json({"error": "amele not found"}, 404)
            return
        updates = {}
        for k in ("name", "description", "model_kind", "model_name", "enabled"):
            if k in data and data[k] is not None:
                updates[k] = data[k].strip() if isinstance(data[k], str) else data[k]
        if "model_cfg" in data:
            updates["model_cfg"] = (data["model_cfg"]
                                    if isinstance(data["model_cfg"], dict) else None)
        if "schema_json" in data:
            updates["schema_json"] = (data["schema_json"]
                                      if isinstance(data["schema_json"], dict) else None)
        if updates.get("model_kind") not in (None, "local", "api"):
            self._json({"error": "model_kind: local|api"}, 400)
            return
        db.update_amele(amele["id"], updates)
        if "name" in updates or "description" in updates:
            yaml_path = self.server.ameles_dir / f"{amele['slug']}.yaml"
            yaml_path.write_text(self._amele_yaml_text(
                amele["slug"],
                updates.get("name", amele["name"]),
                updates.get("description", amele["description"])), encoding="utf-8")
        db.log("web", {"event": "amele_edited", "amele": amele["slug"]})
        self._json({"ok": True})

    def _v2_ameles_delete(self):
        data = self._read_body()
        db = self.server.db
        amele = db.get_amele(int(data.get("id") or 0))
        if not amele:
            self._json({"error": "amele not found"}, 404)
            return
        db.delete_amele(amele["id"])
        yaml_path = self.server.ameles_dir / f"{amele['slug']}.yaml"
        if yaml_path.exists():
            yaml_path.unlink()
        db.log("web", {"event": "amele_deleted", "amele": amele["slug"]})
        self._json({"ok": True})

    # ------------------------------------------------------------- v2: records

    def _v2_records_get(self):
        db = self.server.db
        amele_id = self._query("amele_id")
        amele_id = int(amele_id) if amele_id else None
        q = (self._query("q") or "").strip().lower()
        rows = db.list_records(amele_id)
        if q:
            rows = [r for r in rows
                    if q in json.dumps(r["data"], ensure_ascii=False).lower()]
        names = {a["id"]: a for a in db.list_ameles()}
        for r in rows:
            a = names.get(r["amele_id"])
            r["amele_slug"] = a["slug"] if a else "?"
            r["amele_name"] = a["name"] if a else "?"
        self._json({"records": rows})

    def _v2_records_create(self):
        data = self._read_body()
        db = self.server.db
        amele_id = int(data.get("amele_id") or 0)
        record_data = data.get("data")
        if not db.get_amele(amele_id):
            self._json({"error": "amele not found"}, 404)
            return
        if not isinstance(record_data, dict):
            self._json({"error": "data: JSON object required"}, 400)
            return
        rid = db.add_record(amele_id, record_data)
        db.log("web", {"event": "record_created", "record_id": rid})
        self._json({"ok": True, "id": rid}, 201)

    def _v2_records_edit(self):
        data = self._read_body()
        db = self.server.db
        rid = int(data.get("id") or 0)
        record_data = data.get("data")
        if not db.get_record(rid):
            self._json({"error": "record not found"}, 404)
            return
        if not isinstance(record_data, dict):
            self._json({"error": "data: JSON object required"}, 400)
            return
        db.update_record(rid, record_data)
        db.log("web", {"event": "record_edited", "record_id": rid})
        self._json({"ok": True})

    def _v2_records_delete(self):
        data = self._read_body()
        db = self.server.db
        rid = int(data.get("id") or 0)
        if not db.get_record(rid):
            self._json({"error": "record not found"}, 404)
            return
        db.delete_record(rid)
        db.log("web", {"event": "record_deleted", "record_id": rid})
        self._json({"ok": True})

    # ------------------------------------------------------------ v2: approvals

    def _v2_approvals_get(self):
        db = self.server.db
        out = []
        for pa in db.list_pending_actions("waiting"):
            amele = db.get_amele(pa["amele_id"])
            out.append({**pa,
                        "amele_slug": amele["slug"] if amele else "?",
                        "amele_name": amele["name"] if amele else "?"})
        self._json({"approvals": out})

    def _v2_approvals_resolve(self):
        data = self._read_body()
        db = self.server.db
        action_id = int(data.get("id") or 0)
        karar = str(data.get("karar") or "").strip().lower()
        pa = db.get_pending_action(action_id)
        if not pa:
            self._json({"error": "onay bulunamadı"}, 404)
            return
        if pa["status"] != "waiting":
            self._json({"error": "bu onay zaten karara bağlanmış"}, 400)
            return
        if karar not in ("approved", "cancelled"):
            self._json({"error": "karar: approved|cancelled"}, 400)
            return
        if karar == "approved":
            amele = db.get_amele(pa["amele_id"])
            yaml_path = (self.server.ameles_dir / f"{amele['slug']}.yaml"
                         if amele else None)
            if yaml_path and yaml_path.exists():
                task = (f"Owner's approval reply: APPROVED.\n"
                        f"Your pending action was:\n"
                        f"{json.dumps(pa['action'], ensure_ascii=False)}\n\n"
                        f"Continue accordingly (e.g. save the record, send "
                        f"the message, or drop it). Reply with a short "
                        f"confirmation.")
                try:
                    run_amele(self.server.cfg, yaml_path, task, timeout_s=120)
                except AmeleError as e:
                    db.log("web", {"event": "approval_forward_failed",
                                   "action_id": action_id, "error": str(e)})
                    self._json({"error": f"amele: {e}"}, 502)
                    return
        db.resolve_pending_action(action_id, karar)
        db.log("web", {"event": "approval_resolved",
                       "action_id": action_id, "status": karar})
        self._json({"ok": True})

    # --------------------------------------------------------------- v2: mcp

    MCP_NAME_RE = re.compile(r"^[a-z0-9_-]{1,32}$")

    def _mcp_liability_ok(self) -> bool:
        return self.server.cfg.mcp_liability_accepted

    def _mcp_block_yaml(self, servers: list[dict]) -> str:
        """Bağlı sunuculardan amele YAML'sına eklenecek mcp: bloğunu üretir."""
        lines = ["mcp:", "  servers:"]
        for s in servers:
            lines.append(f"    - name: {s['name']}")
            lines.append(f"      required: {str(bool(s.get('required', 1))).lower()}")
            lines.append("      transport:")
            lines.append(f"        type: {s['kind']}")
            if s["kind"] == "http":
                if s.get("url"):
                    lines.append(f"        url: {s['url']}")
                hdrs = {}
                if s.get("headers"):
                    try:
                        hdrs = json.loads(s["headers"]) or {}
                    except (TypeError, json.JSONDecodeError):
                        hdrs = {}
                if hdrs:
                    lines.append("        headers:")
                    for k, v in hdrs.items():
                        lines.append(f'          {k}: "{v}"')
            else:
                if s.get("command"):
                    lines.append(f"        command: {s['command']}")
                if s.get("env"):
                    lines.append(f"        env: {s['env']}")
            inc = exc = []
            if s.get("tools_include"):
                try:
                    inc = json.loads(s["tools_include"]) or []
                except (TypeError, json.JSONDecodeError):
                    inc = []
            if s.get("tools_exclude"):
                try:
                    exc = json.loads(s["tools_exclude"]) or []
                except (TypeError, json.JSONDecodeError):
                    exc = []
            if inc or exc:
                lines.append("      tools:")
                if inc:
                    lines.append(f"        include: {json.dumps(inc, ensure_ascii=False)}")
                if exc:
                    lines.append(f"        exclude: {json.dumps(exc, ensure_ascii=False)}")
            auth = None
            if s.get("auth"):
                try:
                    auth = json.loads(s["auth"]) or {}
                except (TypeError, json.JSONDecodeError):
                    auth = {}
            if auth:
                lines.append("      auth:")
                lines.append("        type: oauth")
                if auth.get("client_id"):
                    lines.append(f"        client_id: {auth['client_id']}")
                if auth.get("scopes"):
                    lines.append(f"        scopes: {json.dumps(auth['scopes'], ensure_ascii=False)}")
        return "\n".join(lines)

    def _mcp_sync_yaml(self, amele: dict) -> None:
        """Amele YAML'sındaki mcp bloğunu bağlı sunuculara göre yeniden yazar."""
        path = self.server.ameles_dir / f"{amele['slug']}.yaml"
        if not path.exists():
            return
        text = path.read_text(encoding="utf-8")
        # mevcut mcp bloğunu çıkar ("mcp:" satırı girintisiz, sonraki girintili satırlar)
        lines, out, skipping = text.splitlines(), [], False
        for ln in lines:
            if not skipping and re.match(r"^mcp:\s*$", ln):
                skipping = True
                continue
            if skipping:
                if ln and not ln[0].isspace():
                    skipping = False
                else:
                    continue
            out.append(ln)
        text = "\n".join(out).rstrip() + "\n"
        servers = self.server.db.list_amele_mcp(amele["id"])
        if servers:
            text += self._mcp_block_yaml(servers) + "\n"
        path.write_text(text, encoding="utf-8")

    def _smithery_get(self, path: str) -> dict:
        """registry.smithery.ai'ye UA'lı GET (403 engelini aşar)."""
        req = urllib.request.Request(
            f"https://registry.smithery.ai{path}",
            headers={"User-Agent": "Mozilla/5.0 (X11; Linux x86_64) "
                                   "AppleWebKit/537.36 (KHTML, like Gecko) "
                                   "Chrome/126.0 Safari/537.36"})
        with urllib.request.urlopen(req, timeout=20) as r:
            return json.loads(r.read().decode())

    def _v2_mcp_search(self):
        """Smithery katalog araması (registry public; anahtar gerekmez)."""
        q = (self._query("q") or "").strip()
        if not q:
            self._json({"results": []})
            return
        try:
            data = self._smithery_get(f"/servers?q={urllib.parse.quote(q)}")
        except Exception as e:
            self._json({"error": f"Smithery: {e}", "results": []}, 502)
            return
        results = []
        for s in data.get("servers", [])[:15]:
            conn = (s.get("connections") or [{}])[0]
            results.append({
                "qualified_name": s.get("qualifiedName", ""),
                "display_name": s.get("displayName", ""),
                "description": (s.get("description") or "")[:300],
                "verified": bool(s.get("verified")),
                "use_count": s.get("useCount", 0),
                "remote": bool(s.get("remote")),
                "deployment_url": conn.get("deploymentUrl") if conn.get("type") == "http" else None,
                "tool_count": len(s.get("tools") or []),
            })
        self._json({"results": results})

    def _v2_mcp_servers_create(self):
        data = self._read_body()
        db = self.server.db
        if not self._mcp_liability_ok():
            self._json({"error": "liability_not_accepted"}, 403)
            return
        # Katalogdan: qualified_name verildiyse deployment bilgisi registry'den çekilir
        qualified = (data.get("smithery_qualified_name") or "").strip()
        if qualified:
            name = qualified.split("/")[-1].lower()[:32]
            name = re.sub(r"[^a-z0-9_-]", "-", name)
            url = None
            try:
                meta = self._smithery_get(f"/servers/{urllib.parse.quote(qualified)}")
                for c in meta.get("connections") or []:
                    if c.get("type") == "http" and c.get("deploymentUrl"):
                        url = c["deploymentUrl"]
                        break
            except Exception as e:
                self._json({"error": f"Smithery: {e}"}, 502)
                return
            if not url:
                self._json({"error": "sunucuda http bağlantısı yok (stdio sunucular için elle ekleyin)"}, 400)
                return
            if db.get_mcp_server_by_name(name):
                self._json({"error": f"'{name}' zaten kayıtlı"}, 409)
                return
            server_id = db.add_mcp_server(
                name, "http", url=url,
                headers={"Authorization": "Bearer ${SMITHERY_API_KEY}"},
                required=1 if data.get("required", True) else 0,
                tools_include=data.get("tools_include") or None,
                tools_exclude=data.get("tools_exclude") or None)
            db.log("web", {"event": "mcp_server_created", "server": name,
                           "source": "smithery"})
            self._json({"ok": True, "id": server_id, "name": name,
                        "url": url, "smithery": True}, 201)
            return
        # Elle ekleme
        name = (data.get("name") or "").strip().lower()
        kind = (data.get("kind") or "").strip().lower()
        if not self.MCP_NAME_RE.match(name):
            self._json({"error": "name: 1-32 chars, a-z0-9_-"}, 400)
            return
        if kind not in ("stdio", "http"):
            self._json({"error": "kind: stdio|http"}, 400)
            return
        if db.get_mcp_server_by_name(name):
            self._json({"error": f"'{name}' zaten kayıtlı"}, 409)
            return
        if kind == "http":
            url = (data.get("url") or "").strip()
            if not url:
                self._json({"error": "url gerekli (http)"}, 400)
                return
            command = None
        else:
            command = data.get("command")
            if isinstance(command, str):
                try:
                    command = json.loads(command)
                except json.JSONDecodeError:
                    command = [c.strip() for c in command.split() if c.strip()]
            if not isinstance(command, list) or not command:
                self._json({"error": "command gerekli (stdio): argv dizisi"}, 400)
                return
            command = json.dumps(command, ensure_ascii=False)
            url = None
        headers = data.get("headers") if isinstance(data.get("headers"), dict) else None
        auth = data.get("auth") if isinstance(data.get("auth"), dict) else None
        tools_include = (data.get("tools_include")
                         if isinstance(data.get("tools_include"), list) else None)
        tools_exclude = (data.get("tools_exclude")
                         if isinstance(data.get("tools_exclude"), list) else None)
        env = data.get("env") if isinstance(data.get("env"), list) else None
        server_id = db.add_mcp_server(
            name, kind, command=command, url=url, headers=headers, env=env,
            auth=auth, tools_include=tools_include, tools_exclude=tools_exclude,
            required=1 if data.get("required", True) else 0)
        db.log("web", {"event": "mcp_server_created", "server": name, "source": "manual"})
        self._json({"ok": True, "id": server_id, "name": name}, 201)

    def _v2_mcp_servers_delete(self):
        data = self._read_body()
        db = self.server.db
        srv = db.get_mcp_server(int(data.get("id") or 0))
        if not srv:
            self._json({"error": "sunucu bulunamadı"}, 404)
            return
        # bağlı amelesden YAML'ı temizle
        for a in db.list_ameles():
            if any(b["id"] == srv["id"] for b in db.list_amele_mcp(a["id"])):
                self._mcp_sync_yaml(a)
        db.delete_mcp_server(srv["id"])
        db.log("web", {"event": "mcp_server_deleted", "server": srv["name"]})
        self._json({"ok": True})

    def _v2_mcp_bind(self):
        data = self._read_body()
        db = self.server.db
        if not self._mcp_liability_ok():
            self._json({"error": "liability_not_accepted"}, 403)
            return
        amele = db.get_amele(int(data.get("amele_id") or 0))
        srv = db.get_mcp_server(int(data.get("server_id") or 0))
        if not amele or not srv:
            self._json({"error": "amele veya sunucu bulunamadı"}, 404)
            return
        db.bind_amele_mcp(amele["id"], srv["id"])
        self._mcp_sync_yaml(amele)
        db.log("web", {"event": "mcp_bound", "server": srv["name"],
                       "amele": amele["slug"]})
        self._json({"ok": True})

    def _v2_mcp_unbind(self):
        data = self._read_body()
        db = self.server.db
        amele = db.get_amele(int(data.get("amele_id") or 0))
        srv = db.get_mcp_server(int(data.get("server_id") or 0))
        if not amele or not srv:
            self._json({"error": "amele veya sunucu bulunamadı"}, 404)
            return
        db.unbind_amele_mcp(amele["id"], srv["id"])
        self._mcp_sync_yaml(amele)
        db.log("web", {"event": "mcp_unbound", "server": srv["name"],
                       "amele": amele["slug"]})
        self._json({"ok": True})

    def _v2_mcp_explain(self):
        """Bağlı amelenin YAML'ı ile `amele explain` — MCP sunucuları gerçekten
        bağlanır, katkılarını listeler ."""
        data = self._read_body()
        db = self.server.db
        amele = db.get_amele(int(data.get("amele_id") or 0))
        srv = db.get_mcp_server(int(data.get("server_id") or 0))
        if not amele or not srv:
            self._json({"error": "amele veya sunucu bulunamadı"}, 404)
            return
        bound = [b["id"] for b in db.list_amele_mcp(amele["id"])]
        if srv["id"] not in bound:
            self._json({"error": "sunucu bu ameleye bağlı değil"}, 400)
            return
        yaml_path = self.server.ameles_dir / f"{amele['slug']}.yaml"
        if not yaml_path.exists():
            self._json({"error": "YAML yok"}, 404)
            return
        env = {**os.environ, "AMELE_MODEL": "x", "PROVIDER_TYPE": "openai",
               "BASE_URL": "http://localhost:11434/v1", "API_KEY": "x",
               "KAHYA_LANGUAGE_NAME": "English"}
        try:
            proc = subprocess.run(
                [str(self.server.cfg.amele_bin), "explain", str(yaml_path)],
                capture_output=True, text=True, env=env, timeout=60)
            out = proc.stdout + (proc.stderr or "")
            ok = proc.returncode == 0
            db.log("web", {"event": "mcp_explain", "server": srv["name"],
                           "amele": amele["slug"], "ok": ok})
            self._json({"ok": ok, "exit": proc.returncode,
                        "output": out[-4000:]})
        except subprocess.TimeoutExpired:
            self._json({"ok": False, "error": "zaman aşımı (60s)"}, 504)
        except Exception as e:
            self._json({"ok": False, "error": str(e)}, 502)

    def _v2_mcp_status(self):
        """OAuth kimlik durumu: bağlı oauth sunucuları için `amele mcp status`."""
        db = self.server.db
        rows = []
        for s in db.list_mcp_servers():
            auth = {}
            if s.get("auth"):
                try:
                    auth = json.loads(s["auth"]) or {}
                except (TypeError, json.JSONDecodeError):
                    auth = {}
            if not auth:
                continue
            # oauth sunucusu bağlı olan ilk amelenin YAML'ı ile status
            for a in db.list_ameles():
                if any(b["id"] == s["id"] for b in db.list_amele_mcp(a["id"])):
                    yaml_path = self.server.ameles_dir / f"{a['slug']}.yaml"
                    if yaml_path.exists():
                        env = {**os.environ, "KAHYA_LANGUAGE_NAME": "English"}
                        try:
                            proc = subprocess.run(
                                [str(self.server.cfg.amele_bin), "mcp", "status",
                                 str(yaml_path)], capture_output=True, text=True,
                                env=env, timeout=30)
                            rows.append({"server": s["name"], "amele": a["slug"],
                                         "ok": proc.returncode == 0,
                                         "output": (proc.stdout + proc.stderr)[-1500:]})
                        except Exception as e:
                            rows.append({"server": s["name"], "ok": False,
                                         "output": str(e)})
                    break
        self._json({"oauth_status": rows})

    def _v2_mcp_login(self):
        """OAuth login TTY ister — panel terminalde çalıştırılacak komutu verir."""
        data = self._read_body()
        db = self.server.db
        srv = db.get_mcp_server(int(data.get("server_id") or 0))
        if not srv:
            self._json({"error": "sunucu bulunamadı"}, 404)
            return
        auth = {}
        if srv.get("auth"):
            try:
                auth = json.loads(srv["auth"]) or {}
            except (TypeError, json.JSONDecodeError):
                auth = {}
        if not auth:
            self._json({"error": "bu sunucu oauth kullanmıyor (statik header yeterli)"}, 400)
            return
        # oauth sunucusu bağlı olan ilk amelenin YAML'ı
        yaml_path = None
        for a in db.list_ameles():
            if any(b["id"] == srv["id"] for b in db.list_amele_mcp(a["id"])):
                yaml_path = self.server.ameles_dir / f"{a['slug']}.yaml"
                break
        if not yaml_path or not yaml_path.exists():
            self._json({"error": "önce sunucuyu bir ameleye bağlayın"}, 400)
            return
        cmd = (f"cd {self.server.cfg.dir} && {self.server.cfg.amele_bin} "
               f"mcp login {yaml_path} {srv['name']}")
        db.log("web", {"event": "mcp_login_hint", "server": srv["name"]})
        self._json({"ok": True, "command": cmd})

    # -------------------------------------------------------------- v2: tasks

    def _v2_tasks_get(self):
        db = self.server.db
        status = self._query("status") or None
        rows = []
        for t in db.list_scheduled_tasks(status):
            amele = db.get_amele(t["amele_id"])
            r = dict(t)
            r["amele_slug"] = amele["slug"] if amele else "?"
            rows.append(r)
        self._json({"tasks": rows})

    # --------------------------------------------------------------- v2: mcp

    def _v2_mcp_get(self):
        db = self.server.db
        # sunucu → amele slug haritası (amele_mcp)
        binds = {}
        for row in db.con.execute(
                "SELECT a.server_id, m.slug FROM amele_mcp a "
                "JOIN ameles m ON m.id = a.amele_id").fetchall():
            binds.setdefault(row["server_id"], []).append(row["slug"])
        out = []
        for s in db.list_mcp_servers():
            d = dict(s)
            try:
                d["headers"] = json.loads(d.get("headers") or "{}")
            except (TypeError, json.JSONDecodeError):
                d["headers"] = {}
            d["ameles"] = binds.get(s["id"], [])
            out.append(d)
        self._json({"mcp_servers": out})

    # ----------------------------------------------------------- settings

    def _save_settings(self):
        data = self._read_body().get("settings") or {}
        problems = self.server.cfg.save_settings(data)
        if problems:
            self._json({"error": "; ".join(problems)}, 400)
            return
        self.server.db.log("web", {"event": "settings_saved",
                                   "keys": list(data.keys())})
        self._json({"ok": True, "settings": self.server.cfg.all_editable()})

    def _test_telegram(self):
        cfg = self.server.cfg
        data = self._read_body()
        # Use the values typed in the panel form (unsaved) when provided —
        # testing must work before the user hits Save.
        token = str(data.get("token") or "").strip() or cfg.telegram_token
        chat = str(data.get("chat_id") or "").strip() or cfg.telegram_chat_id
        if not token or not chat:
            self._json({"error": "token/chat id eksik"}, 400)
            return
        tmp = type("Cfg", (), {"telegram_token": token, "telegram_chat_id": chat})()
        msg = I18n(self.server.cfg.dir / "lang", self.server.cfg.language).t(
            "panel.test_message")
        ok = _telegram_send_factory(tmp)(msg)
        self._json({"ok": ok == "ok", "detail": ok if ok != "ok" else ""})

    def _test_llm(self):
        cfg = self.server.cfg
        data = self._read_body()
        # Use the values typed in the panel form (unsaved) when provided.
        overrides = {
            "model": str(data.get("model") or "").strip() or cfg.model,
            "provider_type": str(data.get("provider_type") or "").strip()
                              or cfg.provider_type,
            "base_url": str(data.get("base_url") or "").strip() or cfg.base_url,
        }
        if data.get("api_key"):
            overrides["api_key"] = str(data["api_key"]).strip()
        probe_cfg = Config(self.server.db, overrides=overrides)
        if not probe_cfg.model or not probe_cfg.base_url:
            self._json({"error": "model/endpoint eksik"}, 400)
            return
        probe = self.server.ameles_dir / "extract-amele.yaml"
        try:
            res = run_amele(probe_cfg, probe, "test: 1 TL trial invoice", timeout_s=60)
            self._json({"ok": True, "detail": str(res)[:200]})
        except AmeleError as e:
            self._json({"error": f"amele exit {e.exit_code}: {e}", "ok": False}, 502)
        except Exception as e:
            self._json({"error": str(e), "ok": False}, 502)

    def log_message(self, fmt, *args):  # quieter
        pass


def serve(cfg: Config, db: KahyaDB):
    handler = type("H", (Handler,), {})
    srv = ThreadingHTTPServer(("0.0.0.0", cfg.web_port), handler)
    srv.db = db
    srv.cfg = cfg
    srv.web_dir = cfg.dir / "web"
    srv.ameles_dir = cfg.ameles_dir
    srv.telegram_send = _telegram_send_factory(cfg)
    print(f"[kahya web] panel on http://0.0.0.0:{cfg.web_port}/")
    try:
        srv.serve_forever()
    except KeyboardInterrupt:
        print("\nbye")


def _telegram_send_factory(cfg: Config):
    import urllib.parse
    import urllib.request

    def send(text: str) -> str:
        token = cfg.telegram_token
        chat = cfg.telegram_chat_id
        if not token or not chat:
            return "HATA: token/chat id eksik"
        base = __import__("os").environ.get("TELEGRAM_API_BASE", "https://api.telegram.org")
        url = f"{base}/bot{token}/sendMessage"
        text = text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        data = urllib.parse.urlencode({
            "chat_id": chat, "text": text, "parse_mode": "HTML",
            "disable_web_page_preview": "true"}).encode()
        try:
            with urllib.request.urlopen(urllib.request.Request(url, data=data), timeout=30):
                return "ok"
        except Exception as e:
            return f"HATA: {e}"
    return send


if __name__ == "__main__":
    _db = KahyaDB(Config().db_path)
    _cfg = Config(_db)
    try:
        serve(_cfg, _db)
    finally:
        _db.close()
