"""Web panel — REST API + static single-page UI.

The visual layer of "organization as code": creating an agent from the
panel writes agents/<slug>.yaml (an amele agent) and a database row.
Deleting an agent is deleting a file + row. Everything else the panel
does (items, settings, history) is plain CRUD on the same SQLite file
the scheduler and bot use.

Auth: PBKDF2-hashed panel password, session cookie, brute-force lockout
(5 failed attempts → 5 min), env fallback (KAHYA_ADMIN_PASSWORD).
"""
from __future__ import annotations

import json
import re
import secrets
from http.cookies import SimpleCookie
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import parse_qs, urlparse

from .amele_runner import AmeleError, run_agent
from .config import Config, DEFAULT_ADMIN_PASSWORD, hash_password, verify_password
from .db import KahyaDB
from .i18n import I18n

AGENT_TEMPLATE = """# {slug} — {name}
# Generated by the Kahya web panel. This file IS the agent — version it,
# diff it, share it ("organization as code").
#
# The scheduler hands it REMINDER tasks:
#   REMINDER item_id=<id> due=<YYYY-MM-DD> today=<YYYY-MM-DD>

model: ${{AMELE_MODEL}}

provider:
  type: ${{PROVIDER_TYPE}}
  base_url: ${{BASE_URL}}
  api_key: ${{API_KEY}}

system_prompt: |
{role_prompt}
  Standard rules for every Kahya agent:
  - You receive REMINDER tasks in the form above, one at a time.
    For each: fetch the record with db_get (op=item, id=<id>), then send
    ONE short message with telegram_send — what it is, when it is due,
    and a clear note if due is today or already overdue (overdue: ask the
    owner to reply "ödedim" once handled).
  - Never invent records, dates or amounts. Never write to the database.

workspace: .

tools:
  fs: false
  subprocess:
    - name: db_get
      description: >
        Read a record from the Kahya database. stdin: JSON — either
        {{"op": "item", "id": <int>}} to fetch one item, or
        {{"op": "items", "agent": "<slug>", "status": "open"}} to list.
        stdout: the record(s) as JSON.
      command: ["../tools/db_get.py"]
      timeout: 30s
    - name: telegram_send
      description: >
        Send a text message to the owner on Telegram. stdin: the message
        text. stdout: "ok" or an error message.
      command: ["../tools/telegram_send.py"]
      timeout: 60s

limits:
  max_turns: 10
  max_tokens: 20000
  timeout: 3m
"""

SLUG_RE = re.compile(r"^[a-z0-9][a-z0-9-]{1,30}$")
MAX_FAILED = 5
LOCK_MINUTES = 5
COOKIE = "kahya_session"


class Handler(BaseHTTPRequestHandler):
    server_version = "Kahya/0.2"

    # ---------------------------------------------------------- helpers

    def _json(self, obj, code=200):
        body = json.dumps(obj, ensure_ascii=False).encode()
        self.send_response(code)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def _read_body(self) -> dict:
        length = int(self.headers.get("Content-Length") or 0)
        if not length:
            return {}
        try:
            return json.loads(self.rfile.read(length).decode() or "{}")
        except json.JSONDecodeError:
            return {}

    def _query(self, key: str):
        vals = parse_qs(urlparse(self.path).query).get(key)
        return vals[0] if vals else None

    def _session_token(self) -> str | None:
        raw = self.headers.get("Cookie") or ""
        c = SimpleCookie()
        c.load(raw)
        m = c.get(COOKIE)
        return m.value if m else None

    def _authed(self) -> bool:
        token = self._session_token()
        return bool(token) and self.server.db.session_valid(token)

    def _require_auth(self) -> bool:
        if self._authed():
            return True
        if self.path == "/login" or self.path == "/api/login":
            return True
        self._json({"error": "unauthorized"}, 401)
        return False

    # ------------------------------------------------------------ routes

    def do_GET(self):
        path = urlparse(self.path).path
        if path == "/login":
            self._serve_web()
            return
        if path == "/" or path == "/index.html":
            self._serve_web()
            return
        if path == "/api/lang":
            lang = self._query("lang") or self.server.cfg.language
            self._json(I18n(self.server.cfg.dir / "lang", lang).data())
            return
        if not self._require_auth():
            return
        if path == "/api/me":
            self._json({"ok": True,
                        "using_default_password": self.server.cfg.admin_password_hash == ""
                                                   and self.server.cfg.env_admin_password() is None})
            return
        if path == "/api/agents":
            self._json({"agents": self.server.db.list_agents()})
            return
        if path == "/api/items":
            q = self.server.db.list_items(
                agent_slug=self._query("agent"), status=self._query("status"))
            self._json({"items": q})
            return
        if path == "/api/logs":
            rows = self.server.db.con.execute(
                "SELECT * FROM logs ORDER BY id DESC LIMIT 100").fetchall()
            self._json({"logs": [dict(r) for r in rows]})
            return
        if path == "/api/settings":
            self._json({"settings": self.server.cfg.all_editable()})
            return
        if path == "/api/backup":
            self._send_backup()
            return
        self._json({"error": "not found"}, 404)

    def do_POST(self):
        path = urlparse(self.path).path
        if path == "/api/login":
            self._login()
            return
        if path == "/api/logout":
            self._logout()
            return
        if not self._require_auth():
            return
        if path == "/api/agents":
            self._create_agent()
            return
        if path == "/api/agents/delete":
            self._delete_agent()
            return
        if path == "/api/agents/edit":
            self._edit_agent()
            return
        if path == "/api/items":
            self._create_item()
            return
        if path.endswith("/complete"):
            self._complete_item(path)
            return
        if path == "/api/settings":
            self._save_settings()
            return
        if path == "/api/test/telegram":
            self._test_telegram()
            return
        if path == "/api/test/llm":
            self._test_llm()
            return
        self._json({"error": "not found"}, 404)

    # -------------------------------------------------------------- auth

    def _login(self):
        db = self.server.db
        if db.failed_logins(LOCK_MINUTES) >= MAX_FAILED:
            self._json({"error": "locked"}, 429)
            return
        data = self._read_body()
        user = str(data.get("user") or "")
        password = str(data.get("password") or "")
        cfg = self.server.cfg

        env_pass = cfg.env_admin_password()
        ok = False
        if env_pass is not None:
            ok = (user == cfg.admin_user and secrets.compare_digest(password, env_pass))
        else:
            stored = cfg.admin_password_hash
            if stored != "":
                ok = (user == cfg.admin_user and verify_password(password, stored))
            else:
                # first run: default credentials, warned in the panel
                ok = (user == cfg.admin_user
                      and secrets.compare_digest(password, DEFAULT_ADMIN_PASSWORD))

        db.record_login(ok)
        if not ok:
            self._json({"error": "bad_credentials"}, 401)
            return
        token = secrets.token_hex(24)
        db.create_session(token)
        self.send_response(200)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Set-Cookie",
                         f"{COOKIE}={token}; HttpOnly; Path=/; Max-Age=86400; SameSite=Lax")
        body = json.dumps({"ok": True}).encode()
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def _logout(self):
        token = self._session_token()
        if token:
            self.server.db.delete_session(token)
        self._json({"ok": True})

    # ------------------------------------------------------------- files

    def _serve_web(self):
        p = self.server.web_dir / "index.html"
        if not p.exists():
            self._json({"error": "web/index.html missing"}, 500)
            return
        body = p.read_bytes()
        self.send_response(200)
        self.send_header("Content-Type", "text/html; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def _send_backup(self):
        db_path = self.server.cfg.db_path
        if not db_path.exists():
            self._json({"error": "db missing"}, 500)
            return
        body = db_path.read_bytes()
        self.send_response(200)
        self.send_header("Content-Type", "application/octet-stream")
        self.send_header("Content-Disposition",
                         f'attachment; filename="kahya-backup-{db_path.stat().st_mtime:.0f}.db"')
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    # ------------------------------------------------------------- agents

    def _agent_yaml_text(self, slug: str, name: str, role_prompt: str) -> str:
        role_indented = "\n".join("  " + ln for ln in role_prompt.splitlines())
        return AGENT_TEMPLATE.format(slug=slug, name=name, role_prompt=role_indented)

    def _create_agent(self):
        data = self._read_body()
        slug = (data.get("slug") or "").strip().lower()
        name = (data.get("name") or "").strip()
        role = (data.get("role_prompt") or "").strip()
        if not SLUG_RE.match(slug):
            self._json({"error": "slug: 2-32 chars, a-z0-9 and dashes only"}, 400)
            return
        if not name or not role:
            self._json({"error": "name and role_prompt are required"}, 400)
            return
        if self.server.db.get_agent_by_slug(slug):
            self._json({"error": f"agent '{slug}' already exists"}, 409)
            return
        yaml_path = self.server.agents_dir / f"{slug}.yaml"
        yaml_path.write_text(self._agent_yaml_text(slug, name, role), encoding="utf-8")
        agent_id = self.server.db.create_agent(slug, name, role, str(yaml_path))
        self.server.db.log("web", {"event": "agent_created", "agent": slug})
        self._json({"ok": True, "id": agent_id, "slug": slug,
                    "yaml": str(yaml_path)}, 201)

    def _delete_agent(self):
        data = self._read_body()
        slug = (data.get("slug") or "").strip().lower()
        agent = self.server.db.get_agent_by_slug(slug)
        if not agent:
            self._json({"error": f"agent '{slug}' not found"}, 404)
            return
        # v2: amele silinince kayıtları ON DELETE CASCADE ile silinir
        self.server.db.delete_amele(agent["id"])
        yaml_path = self.server.agents_dir / f"{slug}.yaml"
        if yaml_path.exists():
            yaml_path.unlink()
        self.server.db.log("web", {"event": "agent_deleted", "agent": slug})
        self._json({"ok": True})

    def _edit_agent(self):
        data = self._read_body()
        slug = (data.get("slug") or "").strip().lower()
        agent = self.server.db.get_agent_by_slug(slug)
        if not agent:
            self._json({"error": f"agent '{slug}' not found"}, 404)
            return
        name = (data.get("name") or agent["name"]).strip()
        role = (data.get("role_prompt") or agent["role_prompt"]).strip()
        self.server.db.update_amele(agent["id"], {"name": name, "description": role})
        yaml_path = self.server.agents_dir / f"{slug}.yaml"
        yaml_path.write_text(self._agent_yaml_text(slug, name, role), encoding="utf-8")
        self.server.db.log("web", {"event": "agent_edited", "agent": slug})
        self._json({"ok": True, "name": name})

    # -------------------------------------------------------------- items

    def _create_item(self):
        data = self._read_body().get("data") or {}
        if not data.get("title"):
            self._json({"error": "title is required"}, 400)
            return
        agent = None
        if data.get("agent"):
            agent = self.server.db.get_agent_by_slug(data["agent"])
            if not agent:
                self._json({"error": f"unknown agent: {data['agent']}"}, 400)
                return
        item_id = self.server.db.insert_item(data, agent_id=agent["id"] if agent else None)
        self._json({"ok": True, "id": item_id}, 201)

    def _complete_item(self, path: str):
        item_id = int(path.split("/")[-2])
        result = self.server.db.complete_item(item_id)
        if not result:
            self._json({"error": "item not found"}, 404)
            return
        self.server.db.log("web", {"event": "item_completed", "item_id": item_id})
        self._json({"ok": True, "item": result})

    # ----------------------------------------------------------- settings

    def _save_settings(self):
        data = self._read_body().get("settings") or {}
        problems = self.server.cfg.save_settings(data)
        if problems:
            self._json({"error": "; ".join(problems)}, 400)
            return
        self.server.db.log("web", {"event": "settings_saved",
                                   "keys": list(data.keys())})
        self._json({"ok": True, "settings": self.server.cfg.all_editable()})

    def _test_telegram(self):
        cfg = self.server.cfg
        data = self._read_body()
        # Use the values typed in the panel form (unsaved) when provided —
        # testing must work before the user hits Save.
        token = str(data.get("token") or "").strip() or cfg.telegram_token
        chat = str(data.get("chat_id") or "").strip() or cfg.telegram_chat_id
        if not token or not chat:
            self._json({"error": "token/chat id eksik"}, 400)
            return
        tmp = type("Cfg", (), {"telegram_token": token, "telegram_chat_id": chat})()
        msg = I18n(self.server.cfg.dir / "lang", self.server.cfg.language).t(
            "panel.test_message")
        ok = _telegram_send_factory(tmp)(msg)
        self._json({"ok": ok == "ok", "detail": ok if ok != "ok" else ""})

    def _test_llm(self):
        cfg = self.server.cfg
        data = self._read_body()
        # Use the values typed in the panel form (unsaved) when provided.
        overrides = {
            "model": str(data.get("model") or "").strip() or cfg.model,
            "provider_type": str(data.get("provider_type") or "").strip()
                              or cfg.provider_type,
            "base_url": str(data.get("base_url") or "").strip() or cfg.base_url,
        }
        if data.get("api_key"):
            overrides["api_key"] = str(data["api_key"]).strip()
        probe_cfg = Config(self.server.db, overrides=overrides)
        if not probe_cfg.model or not probe_cfg.base_url:
            self._json({"error": "model/endpoint eksik"}, 400)
            return
        probe = self.server.agents_dir / "extract.yaml"
        try:
            res = run_agent(probe_cfg, probe, "test: 1 TL deneme faturası", timeout_s=60)
            self._json({"ok": True, "detail": str(res)[:200]})
        except AmeleError as e:
            self._json({"error": f"amele exit {e.exit_code}: {e}", "ok": False}, 502)
        except Exception as e:
            self._json({"error": str(e), "ok": False}, 502)

    def log_message(self, fmt, *args):  # quieter
        pass


def serve(cfg: Config, db: KahyaDB):
    handler = type("H", (Handler,), {})
    srv = ThreadingHTTPServer(("0.0.0.0", cfg.web_port), handler)
    srv.db = db
    srv.cfg = cfg
    srv.web_dir = cfg.dir / "web"
    srv.agents_dir = cfg.agents_dir
    srv.telegram_send = _telegram_send_factory(cfg)
    print(f"[kahya web] panel on http://0.0.0.0:{cfg.web_port}/")
    try:
        srv.serve_forever()
    except KeyboardInterrupt:
        print("\nbye")


def _telegram_send_factory(cfg: Config):
    import urllib.parse
    import urllib.request

    def send(text: str) -> str:
        token = cfg.telegram_token
        chat = cfg.telegram_chat_id
        if not token or not chat:
            return "HATA: token/chat id eksik"
        base = __import__("os").environ.get("TELEGRAM_API_BASE", "https://api.telegram.org")
        url = f"{base}/bot{token}/sendMessage"
        text = text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        data = urllib.parse.urlencode({
            "chat_id": chat, "text": text, "parse_mode": "HTML",
            "disable_web_page_preview": "true"}).encode()
        try:
            with urllib.request.urlopen(urllib.request.Request(url, data=data), timeout=30):
                return "ok"
        except Exception as e:
            return f"HATA: {e}"
    return send


if __name__ == "__main__":
    _db = KahyaDB(Config().db_path)
    _cfg = Config(_db)
    try:
        serve(_cfg, _db)
    finally:
        _db.close()
