"""Web panel — REST API + static single-page UI.

The visual layer of "organization as code": creating an agent from the
panel writes agents/<slug>.yaml (an amele agent) and a database row.
Deleting an agent is deleting a file + row. Everything else the panel
does (items, history) is plain CRUD on the same SQLite file the
scheduler and bot use.
"""
from __future__ import annotations

import json
import re
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import urlparse

from .config import Config
from .db import KahyaDB

AGENT_TEMPLATE = """# {slug} — {name}
# Generated by the Kahya web panel. This file IS the agent — version it,
# diff it, share it ("organization as code").
#
# The scheduler hands it REMINDER tasks:
#   REMINDER item_id=<id> due=<YYYY-MM-DD> today=<YYYY-MM-DD>

model: ${{AMELE_MODEL}}

provider:
  type: ${{PROVIDER_TYPE}}
  base_url: ${{BASE_URL}}
  api_key: ${{API_KEY}}

system_prompt: |
{role_prompt}
  Standard rules for every Kahya agent:
  - You receive REMINDER tasks in the form above, one at a time.
    For each: fetch the record with db_get (op=item, id=<id>), then send
    ONE short message with telegram_send — what it is, when it is due,
    and a clear note if due is today or already overdue (overdue: ask the
    owner to reply "ödedim" once handled).
  - Never invent records, dates or amounts. Never write to the database.

workspace: .

tools:
  fs: false
  subprocess:
    - name: db_get
      description: >
        Read a record from the Kahya database. stdin: JSON — either
        {{"op": "item", "id": <int>}} to fetch one item, or
        {{"op": "items", "agent": "<slug>", "status": "open"}} to list.
        stdout: the record(s) as JSON.
      command: ["./tools/db_get.py"]
      timeout: 30s
    - name: telegram_send
      description: >
        Send a text message to the owner on Telegram. stdin: the message
        text. stdout: "ok" or an error message.
      command: ["./tools/telegram_send.py"]
      timeout: 60s

limits:
  max_turns: 10
  max_tokens: 20000
  timeout: 3m
"""

SLUG_RE = re.compile(r"^[a-z0-9][a-z0-9-]{1,30}$")


class Handler(BaseHTTPRequestHandler):
    server_version = "Kahya/0.1"

    def _json(self, obj, code=200):
        body = json.dumps(obj, ensure_ascii=False).encode()
        self.send_response(code)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def _read_body(self) -> dict:
        length = int(self.headers.get("Content-Length") or 0)
        if not length:
            return {}
        return json.loads(self.rfile.read(length).decode() or "{}")

    # ----------------------------------------------------------

    def do_GET(self):
        path = urlparse(self.path).path
        if path == "/" or path == "/index.html":
            self._serve_web()
            return
        if path == "/api/agents":
            self._json({"agents": self.server.db.list_agents()})
            return
        if path == "/api/items":
            q = self.server.db.list_items(
                agent_slug=self._query("agent"), status=self._query("status"))
            self._json({"items": q})
            return
        if path == "/api/logs":
            rows = self.server.db.con.execute(
                "SELECT * FROM logs ORDER BY id DESC LIMIT 100").fetchall()
            self._json({"logs": [dict(r) for r in rows]})
            return
        self._json({"error": "not found"}, 404)

    def do_POST(self):
        path = urlparse(self.path).path
        if path == "/api/agents":
            self._create_agent()
            return
        if path == "/api/items":
            self._create_item()
            return
        if path.endswith("/complete"):
            self._complete_item(path)
            return
        self._json({"error": "not found"}, 404)

    # ----------------------------------------------------------

    def _query(self, key: str):
        q = urlparse(self.path).query
        from urllib.parse import parse_qs
        vals = parse_qs(q).get(key)
        return vals[0] if vals else None

    def _serve_web(self):
        p = self.server.web_dir / "index.html"
        if not p.exists():
            self._json({"error": "web/index.html missing"}, 500)
            return
        body = p.read_bytes()
        self.send_response(200)
        self.send_header("Content-Type", "text/html; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def _create_agent(self):
        data = self._read_body()
        slug = (data.get("slug") or "").strip().lower()
        name = (data.get("name") or "").strip()
        role = (data.get("role_prompt") or "").strip()
        if not SLUG_RE.match(slug):
            self._json({"error": "slug: 2-32 chars, a-z0-9 and dashes only"}, 400)
            return
        if not name or not role:
            self._json({"error": "name and role_prompt are required"}, 400)
            return
        if self.server.db.get_agent_by_slug(slug):
            self._json({"error": f"agent '{slug}' already exists"}, 409)
            return

        role_indented = "\n".join("  " + ln for ln in role.splitlines())
        yaml_text = AGENT_TEMPLATE.format(slug=slug, name=name, role_prompt=role_indented)
        yaml_path = self.server.agents_dir / f"{slug}.yaml"
        yaml_path.write_text(yaml_text, encoding="utf-8")

        agent_id = self.server.db.create_agent(slug, name, role, str(yaml_path))
        self.server.db.log("web", {"event": "agent_created", "agent": slug})
        self._json({"ok": True, "id": agent_id, "slug": slug,
                    "yaml": str(yaml_path)}, 201)

    def _create_item(self):
        data = self._read_body().get("data") or {}
        if not data.get("title"):
            self._json({"error": "title is required"}, 400)
            return
        agent = None
        if data.get("agent"):
            agent = self.server.db.get_agent_by_slug(data["agent"])
            if not agent:
                self._json({"error": f"unknown agent: {data['agent']}"}, 400)
                return
        item_id = self.server.db.insert_item(data, agent_id=agent["id"] if agent else None)
        self._json({"ok": True, "id": item_id}, 201)

    def _complete_item(self, path: str):
        item_id = int(path.split("/")[-2])
        result = self.server.db.complete_item(item_id)
        if not result:
            self._json({"error": "item not found"}, 404)
            return
        self.server.db.log("web", {"event": "item_completed", "item_id": item_id})
        self._json({"ok": True, "item": result})

    def log_message(self, fmt, *args):  # quieter
        pass


def serve(cfg: Config, db: KahyaDB):
    handler = type("H", (Handler,), {})
    srv = ThreadingHTTPServer(("0.0.0.0", cfg.web_port), handler)
    srv.db = db
    srv.web_dir = cfg.dir / "web"
    srv.agents_dir = cfg.agents_dir
    print(f"[kahya web] panel on http://0.0.0.0:{cfg.web_port}/")
    try:
        srv.serve_forever()
    except KeyboardInterrupt:
        print("\nbye")


if __name__ == "__main__":
    cfg = Config()
    db = KahyaDB(cfg.db_path)
    try:
        serve(cfg, db)
    finally:
        db.close()
